GET http://localhost:3000/orders/account HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjJhZjBjNGU5ZjJmNmZhYWUyMmVkNCIsImlhdCI6MTc2MDgyNTMyOCwiZXhwIjoxNzYxNDMwMTI4fQ.dhdff3sHo7iWD8zJvAkxtMKW4R8PPraL7gr9hPUyGRQ