GET http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWQ1YzgzZjFjNzliMzY3MzQ0NmZkZCIsImlhdCI6MTc2MDM4NjE5NSwiZXhwIjoxNzYwOTkwOTk1fQ.tHdhWQhImVVZsHO2YG2DLzVZpFxunMUvc4vU6w8ncYc