POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWZlZjQ4M2VkZWQ1NWJkYWIzY2Q1NyIsImlhdCI6MTc2MDU1NDg2MiwiZXhwIjoxNzYxMTU5NjYyfQ.qeaqCMpyC1GiHnKL6z9y9RL22sUOx2eKm1I3DYFi4H8

{
    "title": "Bread",
    "description": "test",
    "price": 20.20,
    "stockQty": 100,
    "category": "68eff9cca0c458b3d19c4c64"
}